# Site settings
title: Xiaojie Hu
email: xiaojie.hu@sylu.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  Academic Papers.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jasonhu55.github.io" # the base hostname & protocol for your site
twitter_username: #
github_username:  #

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""